name: Generate Snake Animation

# 24 saatte bir çalışacak.
on:
  schedule:
    - cron: "0 0 * * *"  # Her gün UTC saatiyle 00:00'da çalıştırır
  workflow_dispatch:  # Manuel olarak çalıştırabilmem için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # repository'yi klonlar.
    - name: Checkout Repository
      uses: actions/checkout@v2

    # animasyonunu oluşturur.
    - name: Generate Snake Animation
      uses: Platane/snk@v2.0.0
      with:
        github_user_name: "Hakan-kuru" 
        svg_out_path: "github-contribution-grid-snake.svg"

    # Animasyonun çıktısını repoya gönderir.
    - name: Commit & Push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update Snake Animation"
        file_pattern: "github-contribution-grid-snake.svg"

    # SVG dosyasını GitHub Pages'e gönderir (Opsiyonel)
    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output  # SVG dosyasının bulunduğu dizin

